version: '3.8'

services:
  app:
    build: .
    ports:
      - '3333:3333'
    depends_on:
      - db
    volumes:
    - .:/app
    env_file: ./.env
    command: npm run dev

  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tripsbackend
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: